version: "3.9"

services:

  postgresdb:
      container_name: postgresdb
      image: "postgres:13.3"

      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=1234
        - POSTGRES_DB=rustdb
      volumes:
        - rust_api_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      networks:
        - rust-local-network


  rust_backend:
    container_name: rust_backend
    image: rust-api:1.0.0
    build: .
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:1234@postgresdb:5432/rustdb?sslmode=disable
      - RUST_BACKTRACE=full
    depends_on:
      - postgresdb
    networks:
        - rust-local-network
  
  
networks:
  rust-local-network:
    driver: bridge
volumes:
  rust_api_data: {}